name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version-file: .ruby-version
        bundler-cache: true
    
    - name: Run StandardRB
      run: bundle exec standardrb --parallel
    
    - name: Run specs with coverage
      run: bundle exec rspec
      env:
        COVERAGE: true
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage/